"""Property Unique Changes

Revision ID: 8d8450a74f4a
Revises: be5317de6806
Create Date: 2024-09-05 18:30:22.148481

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8d8450a74f4a'
down_revision = 'be5317de6806'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointment')
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_index('first_name')
        batch_op.drop_index('last_name')
        batch_op.drop_index('phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.create_index('phone', ['phone'], unique=True)
        batch_op.create_index('last_name', ['last_name'], unique=True)
        batch_op.create_index('first_name', ['first_name'], unique=True)

    op.create_table('appointment',
    sa.Column('appointment_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('patient_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('business_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('time', mysql.TIME(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.business_id'], name='appointment_ibfk_2'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], name='appointment_ibfk_1'),
    sa.PrimaryKeyConstraint('appointment_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
