"""Migration 2

Revision ID: b6667d27bd5c
Revises: 03906ee48a52
Create Date: 2024-09-02 12:10:13.779272

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b6667d27bd5c'
down_revision = '03906ee48a52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('appointment_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('business_id', sa.Integer(), nullable=False))
        batch_op.drop_column('app_id')

    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_id', sa.Integer(), nullable=False))
        batch_op.drop_column('id')

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_id', sa.Integer(), nullable=False))
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_column('patient_id')

    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_column('business_id')

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('app_id', mysql.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_column('business_id')
        batch_op.drop_column('appointment_id')

    # ### end Alembic commands ###
